[package]
name = "api-client"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.32"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_with = { version = "3.21.0", features = ["json"] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["full"] }
tracing = "0.1.44"
