[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
client-core = { path = "../client-core" }
tokio = { version = "1.52.3", features = ["full"] }
ratatui = "0.30.1"
futures = "0.3.32"
crossterm = { version = "0.29.0", features = ["event-stream"] }
clap = { version = "4.6.1", features = ["derive"] }
